//Todo: YA TERMINO EL PRIMER SEMESTRE Y COFLA ESTA MUY ANSIOSA, YA QUE TIENE DIFICULTAD DE ATENCIÓN, NO SABE SI VA A APROBAR LAS MATERIAS O NO,LO UNICO QUE SABE ES QUE PARA LOGRARLO, NECESITARA EL 90% DE ASISTENCIAS EL PROMEDIO POR MATERIA DEBE SER POR LO MENOS 7/10 Y DEBE TENER COMO MINIMO EL 75% DE LOS TRABAJOS PRÁCTICOS TERMINADOS 

//?Problema A 
//*Solicitar los datos y decirle si aprueba o reprueba 
//* Mostrar todo esto con colores representativos en consola


//Todo: COFLA ESTA SUFRIENDO UN POCO YA QUE A PESAR DE CONTAR CON EL 90% DE CONTENIDO Y TENER UN PROMEDIO SUPERIOR A 7 DE 10, NO CREE LLEGAR A ENTREGAR EL 75% DE TRABAJOS PRACTICOS A TIEMPO, YA QUE NECESITA DIVIDIR LAS TAREAS QUE HARA SEMANALMENTE, COFLA DEBE TRABAJAR 8 HORAS POR DIA, DURANTE 2 SEMANAS, ENTRE LAS QUE TIENE 24 HORAS PARA ESTUDIAR, 24 PARA HACER TRABAJOS PRACTICOS, 56 HORAS PARA TRABAJAR  Y 8 HORAS PARA HACER LAS COSAS DE LA CASA

//?Problema B
//* Organizar diariamente las tareas
//* Utilizar la consola para organizarlo
//* Cada tarea no debe superar las 4hs   